### ISSUE TITLE
not compatible with Python 3.4 and later, cannot import module

### ISSUE THREAD

**Issue by ryanho** [yen223/lunisolar#2]
always got this error after import module
`>>> import lunisolar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ryan/Envs/mgmt/lib/python3.4/site-packages/lunisolar/__init__.py", line 1, in <module>
    from lunisolar import ChineseDate
ImportError: cannot import name 'ChineseDate'`

ericof already fix this [problem](https://github.com/ericof/lunisolar/commit/f9f7392fd009c896c67f865bf42af35e6f410cc9)

**Comment by Freyja-Folkvangr** [comment]
```
  File "/Users/username/project/subproject/iclock/models.py", line 13, in <module>
    import lunisolar
  File "/Users/username/project/subproject/venv3/lib/python3.9/site-packages/lunisolar/__init__.py", line 1, in <module>
    from lunisolar import ChineseDate
ImportError: cannot import name 'ChineseDate' from partially initialized module 'lunisolar' (most likely due to a circular import) (/Users/username/project/subproject/venv3/lib/python3.9/site-packages/lunisolar/__init__.py)
```
